#!/bin/bash

# Remoção de arquivos de compilaçoes anteriores
sudo rm -rfv $HOME/umate;mkdir -pv $HOME/umate

# Criação do sistema base
sudo debootstrap \
    --arch=amd64 \
    --variant=minbase \
    --components=main,multiverse,universe \
    focal \
    $HOME/umate/chroot
#    --include=fish \

# Primeira etapa da montagem do enjaulamento do sistema base
sudo mount --bind /dev $HOME/umate/chroot/dev
sudo mount --bind /run $HOME/umate/chroot/run
sudo chroot $HOME/umate/chroot mount none -t proc /proc
sudo chroot $HOME/umate/chroot mount none -t devpts /dev/pts
sudo chroot $HOME/umate/chroot sh -c "export HOME=/root"
echo "umate" | sudo tee $HOME/umate/chroot/etc/hostname

# Adição dos repositórios principais do Ubuntu
cat <<EOF | sudo tee $HOME/umate/chroot/etc/apt/sources.list
deb http://us.archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
EOF

# Repositórios adicionais
#sudo chroot $HOME/umate/chroot apt update
#sudo chroot $HOME/umate/chroot apt install -y software-properties-common
# PPA 1
#sudo chroot $HOME/umate/chroot add-apt-repository -yn ppa:usuário/programa
# PPA 2
#sudo chroot $HOME/umate/chroot add-apt-repository -y ppa:usuário/programa
# Google Chrome Apt repo
echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee $HOME/umate/chroot/etc/apt/sources.list.d/google-chrome.list
wget -O- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor | sudo tee $HOME/umate/chroot/etc/apt/trusted.gpg.d/google-chrome.gpg 

# TeamViewer Apt repo
echo 'deb http://linux.teamviewer.com/deb stable main' | sudo tee $HOME/umate/chroot/etc/apt/sources.list.d/teamviewer-temp.list
wget -O- https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc | gpg --dearmor | sudo tee $HOME/umate/chroot/etc/apt/trusted.gpg.d/teamviewer.gpg

# AnyDesk Apt repo
echo 'deb http://deb.anydesk.com/ all main' | sudo tee $HOME/umate/chroot/etc/apt/sources.list.d/anydesk-stable.list
wget -O- https://keys.anydesk.com/repos/DEB-GPG-KEY | gpg --dearmor | sudo tee $HOME/umate/chroot/etc/apt/trusted.gpg.d/anydesk.gpg

# Segunda etapa da montagem do enjaulamento
sudo chroot $HOME/umate/chroot apt update
sudo chroot $HOME/umate/chroot apt install -y systemd-sysv
sudo chroot $HOME/umate/chroot sh -c "dbus-uuidgen > /etc/machine-id"
sudo chroot $HOME/umate/chroot ln -fs /etc/machine-id /var/lib/dbus/machine-id
sudo chroot $HOME/umate/chroot dpkg-divert --local --rename --add /sbin/initctl
sudo chroot $HOME/umate/chroot ln -s /bin/true /sbin/initctl

# Variáveis de ambiente para execução automatizada do script
sudo chroot $HOME/umate/chroot sh -c "echo 'grub-pc grub-pc/install_devices_empty   boolean true' | debconf-set-selections"
sudo chroot $HOME/umate/chroot sh -c "echo 'locales locales/locales_to_be_generated multiselect pt_BR.UTF-8 UTF-8' | debconf-set-selections"
sudo chroot $HOME/umate/chroot sh -c "echo 'locales locales/default_environment_locale select pt_BR.UTF-8' | debconf-set-selections"
sudo chroot $HOME/umate/chroot sh -c "echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections"
sudo chroot $HOME/umate/chroot sh -c "echo 'resolvconf resolvconf/linkify-resolvconf boolean false' | debconf-set-selections"

# Ferramentas base do Ubuntu
sudo chroot $HOME/umate/chroot apt install -y --fix-missing \
    casper \
    discover \
    laptop-detect \
    linux-generic \
    locales \
    lupin-casper \
    net-tools \
    network-manager \
    os-prober \
    resolvconf \
    ubuntu-standard \
    wireless-tools \
    lib32gcc1 \
    grub-efi-amd64-signed

# Ambiente de desktop
sudo chroot $HOME/umate/chroot apt-mark hold gnome-shell
sudo chroot $HOME/umate/chroot apt install -y ubuntu-mate-desktop

# Programas inclusos no sistema
sudo chroot $HOME/umate/chroot apt install -y \
   anydesk \
   bless \
   cifs-utils \
   caja-image-converter \
   caja-rename \
   clamav \
   clamtk \
   filezilla \
   google-chrome-stable \
   grsync \
   hardinfo \
   hwloc \
   inxi \
   iotop \
   netdiscover \
   plymouth-theme-spinner \
   remmina \
   samba \
   samba-common \
   speedtest-cli \
   stress \
   teamviewer \
   dkms \
   bcmwl-kernel-source \
   b43-fwcutter \
   ubuntu-restricted-extras \
   printer-driver-all \
   hplip \
   pinta \
   k3b \
   remmina \
   virtualbox \
   arp-scan \
   testdisk \
   smartmontools \
   guvcview \
   cockpit \
   openssh-server
   
# WINE
sudo chroot $HOME/umate/chroot dpkg --add-architecture i386
sudo chroot $HOME/umate/chroot apt update
sudo chroot $HOME/umate/chroot apt install -y \
   wine \
   wine32
    
# Programas que não estão nos repositórios do Ubuntu
# Angry IP Scan
sudo wget -O $HOME/umate/chroot/ipscan.deb https://github.com/angryip/ipscan/releases/download/3.7.0/ipscan_3.7.0_amd64.deb
sudo chroot $HOME/umate/chroot sh -c "apt install -y ./ipscan.deb";sudo rm -rfv $HOME/umate/chroot/ipscan*.deb

# MATE menu
sudo cp -rfv packages/*.deb $HOME/umate/chroot/
sudo chroot $HOME/umate/chroot apt install -y \
   ./gir1.2-mate-menu_1.24.0-1.1_amd64.deb \
   ./gir1.2-matemenu-2.0_1.24.0-1.1_amd64.deb \
   ./libmate-menu2_1.24.0-1.1_amd64.deb \
   ./mate-menus_1.24.0-1.1_all.deb
sudo rm -rfv $HOME/umate/chroot/*mate*.deb

# Ubiquity(instalador do sistema)
sudo chroot $HOME/umate/chroot apt install -y \
    gparted \
#    ubiquity \
#    ubiquity-casper \
#    ubiquity-frontend-gtk \
#    ubiquity-slideshow-ubuntu-mate

# Remoção de pacotes desnecessários
#sudo chroot $HOME/ubuntu-custom/chroot apt autoremove --purge -y \
#    programa1 \
#    programa2 \
#    programa3

# Atualização do sistema
sudo rm -rfv $HOME/umate/chroot/etc/apt/sources.list.d/teamviewer-temp.list
sudo chroot $HOME/umate/chroot apt dist-upgrade -y

# Configuração do Plymouth
sudo chroot $HOME/umate/chroot sh -c "update-alternatives --set default.plymouth /usr/share/plymouth/themes/bgrt/bgrt.plymouth"
sudo chroot $HOME/umate/chroot update-initramfs -u -k all

# Reconfiguração da rede
sudo chroot $HOME/umate/chroot apt install --reinstall resolvconf
cat <<EOF | sudo tee $HOME/umate/chroot/etc/NetworkManager/NetworkManager.conf
[main]
rc-manager=resolvconf
plugins=ifupdown,keyfile
dns=dnsmasq
[ifupdown]
managed=false
EOF
sudo chroot $HOME/umate/chroot dpkg-reconfigure network-manager

# Desmontagem do enjaulamento
sudo chroot $HOME/umate/chroot truncate -s 0 /etc/machine-id
sudo chroot $HOME/umate/chroot rm /sbin/initctl
sudo chroot $HOME/umate/chroot dpkg-divert --rename --remove /sbin/initctl
sudo chroot $HOME/umate/chroot apt clean
sudo chroot $HOME/umate/chroot rm -rfv /tmp/* ~/.bash_history
sudo chroot $HOME/umate/chroot umount /proc
sudo chroot $HOME/umate/chroot umount /dev/pts
sudo chroot $HOME/umate/chroot sh -c "export HISTSIZE=0"
sudo umount $HOME/umate/chroot/dev
sudo umount $HOME/umate/chroot/run

# Configuração do GRUB
echo "RESUME=none" | sudo tee $HOME/umate/chroot/etc/initramfs-tools/conf.d/resume
echo "FRAMEBUFFER=y" | sudo tee $HOME/umate/chroot/etc/initramfs-tools/conf.d/splash

# Layout português brasileiro para o teclado
sudo sed -i 's/us/br/g' $HOME/umate/chroot/etc/default/keyboard

# Arquivos de configuração do sistema
sudo cp -rfv settings/* $HOME/umate/chroot/

# Criação dos arquivos de inicialização da imagem de instalação
cd $HOME/umate
mkdir -pv image/{boot/grub,casper,isolinux,preseed}
# Kernel
sudo cp chroot/boot/vmlinuz image/casper/vmlinuz
sudo cp chroot/boot/`ls -t1 chroot/boot/ |  head -n 1` image/casper/initrd
touch image/UMate
# GRUB
cat <<EOF > image/isolinux/grub.cfg
search --set=root --file /UMate
insmod all_video
set default="0"
set timeout=15

if loadfont /boot/grub/unicode.pf2 ; then
    insmod gfxmenu
	insmod jpeg
	insmod png
	set gfxmode=auto
	insmod efi_gop
	insmod efi_uga
	insmod gfxterm
	terminal_output gfxterm
fi

menuentry "Ubuntu MATE 20.04 LTS (Normal)" {
   linux /casper/vmlinuz file=/cdrom/preseed/umate.seed boot=casper quiet splash locale=pt_BR ---
   initrd /casper/initrd
}
menuentry "Ubuntu MATE 20.04 LTS (Recovery)" {
   linux /casper/vmlinuz file=/cdrom/preseed/umate.seed boot=casper quiet splash locale=pt_BR recovery ---
   initrd /casper/initrd
}
EOF

# Loopback
cat <<EOF > image/boot/grub/loopback.cfg
menuentry "UMate (Normal)" {
   linux /casper/vmlinuz file=/cdrom/preseed/umate.seed boot=casper quiet splash iso-scan/filename=\${iso_path} locale=pt_BR ---
   initrd /casper/initrd
}
menuentry "UMate (Recovery)" {
   linux /casper/vmlinuz file=/cdrom/preseed/umate.seed boot=casper quiet splash iso-scan/filename=\${iso_path} locale=pt_BR recovery ---
   initrd /casper/initrd
}
EOF

# Preesed
cat <<EOF > image/preseed/umate.seed

# Success command
#d-i ubiquity/success_command string \
sed -i 's/quiet splash/quiet splash loglevel=0 logo.nologo vt.global_cursor_default=0/g' /target/etc/default/grub ; \
chroot /target update-grub
EOF

# Arquivos de manifesto
sudo chroot chroot dpkg-query -W --showformat='${Package} ${Version}\n' | sudo tee image/casper/filesystem.manifest
sudo cp -v image/casper/filesystem.manifest image/casper/filesystem.manifest-desktop
sudo sed -i '/ubiquity/d' image/casper/filesystem.manifest-desktop
sudo sed -i '/casper/d' image/casper/filesystem.manifest-desktop
sudo sed -i '/discover/d' image/casper/filesystem.manifest-desktop
sudo sed -i '/laptop-detect/d' image/casper/filesystem.manifest-desktop
sudo sed -i '/os-prober/d' image/casper/filesystem.manifest-desktop
#echo "\
#programa1 \
#programa2 \
#programa3" | sudo tee image/casper/filesystem.manifest-remove

# SquashFS
sudo mksquashfs chroot image/casper/filesystem.squashfs -comp xz
printf $(sudo du -sx --block-size=1 chroot | cut -f1) > image/casper/filesystem.size

# Definições de disco
cat <<EOF > image/README.diskdefines
#define DISKNAME  UMate
#define TYPE  binary
#define TYPEbinary  1
#define ARCH  amd64
#define ARCHamd64  1
#define DISKNUM  1
#define DISKNUM1  1
#define TOTALNUM  0
#define TOTALNUM0  1
EOF

# Geração do GRUB para imagem de instalação
cd $HOME/umate/image
grub-mkstandalone \
   --format=x86_64-efi \
   --output=isolinux/bootx64.efi \
   --locales="" \
   --fonts="" \
   "boot/grub/grub.cfg=isolinux/grub.cfg"
(
   cd isolinux && \
   dd if=/dev/zero of=efiboot.img bs=1M count=10 && \
   sudo mkfs.vfat efiboot.img && \
   mmd -i efiboot.img efi efi/boot && \
   mcopy -i efiboot.img ./bootx64.efi ::efi/boot/
)
grub-mkstandalone \
   --format=i386-pc \
   --output=isolinux/core.img \
   --install-modules="linux16 linux normal iso9660 biosdisk memdisk search tar ls" \
   --modules="linux16 linux normal iso9660 biosdisk search" \
   --locales="" \
   --fonts="" \
   "boot/grub/grub.cfg=isolinux/grub.cfg"
cat /usr/lib/grub/i386-pc/cdboot.img isolinux/core.img > isolinux/bios.img

# Geração do MD5 interno da imagem de instalação
sudo /bin/bash -c '(find . -type f -print0 | xargs -0 md5sum | grep -v "\./md5sum.txt" > md5sum.txt)'

# Limpeza da build
sudo rm -rfv ../chroot

# Compilação da imagem de instalação
mkdir -pv ../iso
sudo xorriso \
   -as mkisofs \
   -iso-level 3 \
   -full-iso9660-filenames \
   -volid "UMate" \
   -eltorito-boot boot/grub/bios.img \
   -no-emul-boot \
   -boot-load-size 4 \
   -boot-info-table \
   --eltorito-catalog boot/grub/boot.cat \
   --grub2-boot-info \
   --grub2-mbr /usr/lib/grub/i386-pc/boot_hybrid.img \
   -eltorito-alt-boot \
   -e EFI/efiboot.img \
   -no-emul-boot \
   -append_partition 2 0xef isolinux/efiboot.img \
   -output "../iso/umate-20.04-amd64.iso" \
   -graft-points \
      "." \
      /boot/grub/bios.img=isolinux/bios.img \
      /EFI/efiboot.img=isolinux/efiboot.img

# Geração do MD5 externo da imagem de instalação.
md5sum ../iso/umate-20.04-amd64.iso > ../iso/umate-20.04-amd64.md5
