#!/bin/bash

# REMEMBER TO CREATE A DHCP SERVER INSIDE PIHOLE WEB ACCESS!
############################################################

defaultinterface="wlan0"

extrainterface1="interface=wlxd037457c32f3"
extrainterface2="interface=wlx18d6c70d6149"
extrainterface3="interface=wlxd03745867865"

docker pull pihole/pihole:latest

docker stop pihole
docker rm pihole

sudo mkdir -p /srv/containers/pihole/{dnsmasq.d,etc}

echo "$extrainterface1" | sudo tee /srv/containers/pihole/dnsmasq.d/99-interfaces.conf
echo "$extrainterface2" | sudo tee -a /srv/containers/pihole/dnsmasq.d/99-interfaces.conf
echo "$extrainterface3" | sudo tee -a /srv/containers/pihole/dnsmasq.d/99-interfaces.conf

docker run -d \
--name=pihole \
--network host \
--dns 1.0.0.1 \
--dns 8.8.4.4 \
--hostname=pihole \
--no-healthcheck \
--restart=unless-stopped \
--cap-add=NET_ADMIN \
--privileged \
-e INTERFACE="$defaultinterface" \
-e DNSMASQ_LISTENING=single \
-e SERVERIP=127.0.0.1 \
-e WEBPASSWORD="5V06auso" \
-v /etc/localtime:/etc/localtime:ro \
-v /srv/containers/pihole/etc/:/etc/pihole \
-v /srv/containers/pihole/dnsmasq.d/:/etc/dnsmasq.d \
pihole/pihole:latest

sudo iptables -F; sudo iptables -X
sudo iptables -A OUTPUT -j ACCEPT -m comment --comment "Accept all outgoing"
sudo iptables -A INPUT -j ACCEPT -m comment --comment "Accept all incoming"
sudo iptables -A FORWARD -j ACCEPT -m comment --comment "Accept all forwarded"

############################################################

docker pull ghcr.io/ajnart/homarr:latest

docker stop homarr
docker rm homarr

sudo mkdir -p /srv/containers/homarr/{configs,data,icons,backgrounds}

sudo chmod 777 -R /srv/containers/homarr/

sudo systemctl restart docker

docker run -d \
--name=homarr \
--hostname=homarr \
--no-healthcheck \
--restart=unless-stopped \
-p 7575:7575 \
-v /etc/localtime:/etc/localtime:ro \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /srv/containers/homarr/data:/data \
-v /srv/containers/homarr/icons:/app/public/icons \
-v /srv/containers/homarr/configs:/app/data/configs \
-v /srv/containers/homarr/backgrounds:/app/public/imgs/backgrounds \
ghcr.io/ajnart/homarr:latest
# --network host \

############################################################

docker pull germannewsmaker/myspeed

docker stop myspeed
docker rm myspeed

sudo mkdir -p /srv/containers/myspeedtest/data

sudo chmod 777 -R /srv/containers/myspeedtest/data

docker run -d \
--name=myspeed \
--network host \
--hostname=myspeed \
--no-healthcheck \
--restart=unless-stopped \
-p 5216:5216 \
-v /etc/localtime:/etc/localtime:ro \
-v /srv/containers/myspeedtest/data:/myspeed/data \
germannewsmaker/myspeed

############################################################

docker stop openspeedtest
docker rm openspeedtest

docker run -d \
--name=openspeedtest \
--network host \
--no-healthcheck \
-p 3000:3000 \
-v /etc/localtime:/etc/localtime:ro \
--restart unless-stopped \
openspeedtest/latest

############################################################

docker pull louislam/uptime-kuma:1

docker stop kuma
docker rm kuma

sudo mkdir -p /srv/containers/kuma/data

docker run -d \
--name=kuma \
--network host \
--hostname=kuma \
--no-healthcheck \
--restart=unless-stopped \
-e UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true \
-e UPTIME_KUMA_PORT=3002 \
-p 3002:3002 \
-v /etc/localtime:/etc/localtime:ro \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /srv/containers/kuma/data:/app/data \
louislam/uptime-kuma:1

############################################################

IPRPi=$(ip route get 1.1.1.1 | grep -oP 'src \K\S+')

clear
echo "Services Access:"
echo ""
echo "Homarr: $IPRPi:7575"
echo ""
echo "PiHole: $IPRPi/admin"
echo "MySpeed: $IPRPi:5216"
echo "OpenSpeedTest: $IPRPi:3000"
echo "Kuma: $IPRPi:3002"
echo " "
