---
server_url: https://MYVAR1
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090

private_key_path: /var/lib/headscale/private.key
noise:
  private_key_path: /var/lib/headscale/noise_private.key

ip_prefixes:
  - 100.64.0.0/10

disable_check_updates: true

db_type: sqlite3
db_path: /var/lib/headscale/db.sqlite

log:
  format: text
  level: info

dns_config:
  override_local_dns: true
  nameservers:
    - 1.1.1.1
    - 8.8.4.4

  magic_dns: true
  base_domain: hs.srv.local

logtail:
  enabled: false
