#!/bin/bash

echo "Nmap Vulners 1.0"

echo " "
read -p "Insira o IP (ou faixas de IP): " IP
read -p "Insira a Porta (ou faixas de Portas): " porta
echo " "

if [ -z "$porta" ]; then
  nmap --script vulners -Pn $IP
else
  nmap --script vulners -Pn $IP -p "$porta"
fi
